### ISSUE TITLE
Could you please pus the git tags?

### ISSUE THREAD

**Issue by voxik** [documentcloud/closure-compiler#33]
There are not available git tags of recent releases. Would you mind to push them? Thx

**Comment by reefdog** [comment]
Thanks for the heads up @voxik. I just pushed tags for 1.1.9/1.1.10/1.1.11.

The version number in the README wasn't updated for 1.1.9 or 1.1.10, and 1.1.9 was never deployed to rubygems, but I'm not going to rewrite history. We're back on track with 1.1.11.

**Comment by voxik** [comment]
Thank you :+1:
