### ISSUE TITLE
Upgrade to more recent closure version

### ISSUE THREAD

**Issue by joncass** [documentcloud/closure-compiler#50]
Hello,

I'm using the `closure-compiler` gem in one of my projects, and it is choking on an error about `super` class properties. I believe this was fixed in the `google/closure-compiler` repo in their v20170626 release. Would it be possible to upgrade the gem to point to a more recent version of Closure?

Thanks!

**Comment by joncass** [comment]
Hi @knowtheory - I was wondering if you'd had a chance to take a look at this and whether or not you think it's something you'll be able to do in the near future (or if you think there's someone else who would be able to handle it). Thanks in advance!

**Comment by knowtheory** [comment]
Whoops!  Yes, apologies, let's do it!

**Comment by knowtheory** [comment]
@joncass hey, just pulled the most recent version... a few of the tests are failing, but visual inspection of the output looks like it's mostly fine.  I don't have time to update the tests right now (although a pull request would be very welcome!).

I've just pushed out a point release for the 2018-05-06 version of closure compiler.

**Comment by joncass** [comment]
Wow - thanks for the quick turnaround @knowtheory !

I don't think I know enough about exactly what we expect Closure to do to feel confident in updating the tests. I can just update the "expected" values to match the "actual" ones if that's all you're looking for, but if you want any more rigor behind it then it's probably best for you to do it :)
